const https = require('https');

// Helper to call Anthropic Claude API (claude-3-5-sonnet, claude-3-opus, claude-3-5-haiku)
async function analyzeImageWithClaude(apiKey, imageBuffer, mimeType, prompt, model = 'claude-3-5-sonnet-20241022') {
  const base64Data = imageBuffer.toString('base64');
  let cleanMime = mimeType || 'image/jpeg';
  if (cleanMime.includes('jpg')) cleanMime = 'image/jpeg';
  if (!['image/jpeg', 'image/png', 'image/gif', 'image/webp'].includes(cleanMime)) {
    cleanMime = 'image/jpeg';
  }
  const cleanModel = (model || 'claude-3-5-sonnet-20241022').trim();

  const requestBody = JSON.stringify({
    model: cleanModel,
    max_tokens: 1500,
    messages: [
      {
        role: 'user',
        content: [
          {
            type: 'image',
            source: {
              type: 'base64',
              media_type: cleanMime,
              data: base64Data
            }
          },
          {
            type: 'text',
            text: prompt
          }
        ]
      }
    ]
  });

  return new Promise((resolve, reject) => {
    const req = https.request('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey.trim(),
        'anthropic-version': '2023-06-01',
        'Content-Length': Buffer.byteLength(requestBody)
      }
    }, res => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          const parsed = JSON.parse(data);
          if (parsed.error) {
            return reject(new Error(parsed.error.message || 'Claude API Error'));
          }
          if (parsed.content && parsed.content[0] && parsed.content[0].text) {
            resolve(parsed.content[0].text.trim());
          } else {
            reject(new Error('No response text generated by Claude'));
          }
        } catch (e) {
          reject(new Error('Invalid response from Claude API: ' + e.message));
        }
      });
    });

    req.on('error', reject);
    req.write(requestBody);
    req.end();
  });
}

module.exports = { analyzeImageWithClaude };