const https = require('https');

// Helper to call Google Gemini API with selected model, multimodal image + prompt
async function analyzeImageWithGemini(apiKey, imageBuffer, mimeType, prompt, model = 'gemini-3.8-flash') {
  const base64Data = imageBuffer.toString('base64');
  const cleanModel = (model || 'gemini-3.8-flash').trim();
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${cleanModel}:generateContent?key=${apiKey}`;

  const requestBody = JSON.stringify({
    contents: [
      {
        parts: [
          { text: prompt },
          {
            inline_data: {
              mime_type: mimeType || 'image/jpeg',
              data: base64Data
            }
          }
        ]
      }
    ],
    generationConfig: {
      temperature: 0.2,
      maxOutputTokens: 1500
    }
  });

  return new Promise((resolve, reject) => {
    const req = https.request(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(requestBody)
      }
    }, res => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          const parsed = JSON.parse(data);
          if (parsed.error) {
            return reject(new Error(parsed.error.message || 'Gemini API Error'));
          }
          if (parsed.candidates && parsed.candidates[0] && parsed.candidates[0].content) {
            const text = parsed.candidates[0].content.parts.map(p => p.text).join(' ').trim();
            resolve(text);
          } else {
            reject(new Error('No response text generated by Gemini'));
          }
        } catch (e) {
          reject(new Error('Invalid response from Gemini API: ' + e.message));
        }
      });
    });

    req.on('error', reject);
    req.write(requestBody);
    req.end();
  });
}

module.exports = { analyzeImageWithGemini };
