const https = require('https');

// Helper to call Groq Vision API (Llama 3.2 Vision)
async function analyzeImageWithGroq(apiKey, imageBuffer, mimeType, prompt, model = 'llama-3.2-11b-vision-preview') {
  const base64Data = imageBuffer.toString('base64');
  const mime = mimeType || 'image/jpeg';
  const cleanModel = (model || 'llama-3.2-11b-vision-preview').trim();

  const requestBody = JSON.stringify({
    model: cleanModel,
    messages: [
      {
        role: 'user',
        content: [
          { type: 'text', text: prompt },
          {
            type: 'image_url',
            image_url: {
              url: `data:${mime};base64,${base64Data}`
            }
          }
        ]
      }
    ],
    max_tokens: 1500,
    temperature: 0.2
  });

  return new Promise((resolve, reject) => {
    const req = https.request('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey.trim()}`,
        'Content-Length': Buffer.byteLength(requestBody)
      }
    }, res => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        try {
          const parsed = JSON.parse(data);
          if (parsed.error) {
            return reject(new Error(parsed.error.message || 'Groq API Error'));
          }
          if (parsed.choices && parsed.choices[0] && parsed.choices[0].message) {
            const text = parsed.choices[0].message.content.trim();
            resolve(text);
          } else {
            reject(new Error('No response text generated by Groq Vision'));
          }
        } catch (e) {
          reject(new Error('Invalid response from Groq API: ' + e.message));
        }
      });
    });

    req.on('error', reject);
    req.write(requestBody);
    req.end();
  });
}

module.exports = { analyzeImageWithGroq };